# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c6df2643dd82852ae4e3d22625e0a36da5104f9f37752372160e7de857c79658c029f57cb6e7a5b5d37bcf7b57521d541ce43dcb1bc763eeab00228b8e25640

test:
  secret_key_base: 54b071c5b595c6b243df8f144aec9986ac1029ea620e982961550bf699847cfc35b4fe4ef4225e0690463b665ba0e92257d3164ab7c29103df79882094389489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
